dist: trusty

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - libspatialindex-dev

install:
  - pip install -e .

script:
  - python -m pytest --doctest-modules rtree tests/test_*
