dist: trusty

cache:
  - pip
  - apt

language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
      sudo: required
      dist: trusty

addons:
  apt:
    packages:
      - libspatialindex-c3

install:
  - pip install flake8
  - pip install -e .

script:
  - flake8 --ignore=E501 --exclude=rtree/__init__.py rtree/
  - python -m pytest --doctest-modules rtree tests/test_*
