pr:
  branches:
    include:
    - master

jobs:
    #  - template: ./ci/azp/linux.yml
    #  - template: ./ci/azp/win.yml
    #  - template: ./ci/azp/osx.yml
  - template: ./ci/azp/linux-1604-pip.yml
  - template: ./ci/azp/linux-1804-pip.yml

