# -*- mode: yaml -*-

jobs:
- job:
  displayName: Conda - Docker
  pool:
    vmImage: ubuntu-16.04
  container:
      image: ubuntu:trusty
      options: --privileged

  steps:
  - bash: |
      DEBIAN_FRONTEND=noninteractive sudo apt-get update -y -qq
      DEBIAN_FRONTEND=noninteractive sudo apt-get install wget libspatialindex-c3
      wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda config --add channels conda-forge
      conda update -q conda
      conda create -q -n test-environment python=3.6
      source activate test-environment
    displayName: 'Install prerequisites'

  - bash: |
      source activate test-environment
      pip install .
    displayName: 'Install Rtree'

  - bash: |
      source activate test-environment
      pip install pytest numpy
      python -m pytest --doctest-modules rtree tests/test_*
    displayName: 'Run pytest'
