jobs:
- job:
  displayName: ubuntu-16.04–pip
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: sudo apt install libspatialindex-c4v5 python3-pip
    displayName: Install libspatialindex and pip

  - bash: |
      pip3 install setuptools
      pip3 install .
    displayName: pip install

  - bash: |
      pip3 install flake8 pytest numpy
      flake8 --ignore=E501 --exclude=rtree/__init__.py rtree/
      python3 -m pytest --doctest-modules rtree tests/test_*
    displayName: pytest
