jobs:
- job:
  displayName: ubuntu-18.04 – pip test
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - bash: sudo apt install libspatialindex-c4v5 python3-pip
    displayName: Install libspatialindex and pip

  - bash: |
      pip3 install setuptools
      pip3 install .
    displayName: pip install

  - bash: |
      pip3 install pytest numpy
      python3 -m pytest --doctest-modules rtree tests/test_*
    displayName: pytest
